"""
Original Authors of Tcl Scripts  : 
    Silvia Mazzoni, 2006
    adapted from Michael H. Scott, 2003
Tcl Script Translation to Python :
    elastropy.com, 2023    
Purpose : 
    Build fiber rectangular RC section, 1 steel layer top, 1 bot, 1 skin, confined core
    Define a procedure which generates a rectangular reinforced concrete section
    with one layer of steel at the top & bottom, skin reinforcement and a 
    confined core.


Formal arguments
   id - tag for the section that is generated by this procedure
   HSec - depth of section, along local-y axis
   BSec - width of section, along local-z axis
   cH - distance from section boundary to neutral axis of reinforcement
   cB - distance from section boundary to side of reinforcement
   coreID - material tag for the core patch
   coverID - material tag for the cover patches
   steelID - material tag for the reinforcing steel
   numBarsTop - number of reinforcing bars in the top layer
   numBarsBot - number of reinforcing bars in the bottom layer
   numBarsIntTot - TOTAL number of reinforcing bars on the intermediate layers, symmetric about z axis and 2 bars per layer-- needs to be an even integer
   barAreaTop - cross-sectional area of each reinforcing bar in top layer
   barAreaBot - cross-sectional area of each reinforcing bar in bottom layer
   barAreaInt - cross-sectional area of each reinforcing bar in intermediate layer 
   nfCoreY - number of fibers in the core patch in the y direction
   nfCoreZ - number of fibers in the core patch in the z direction
   nfCoverY - number of fibers in the cover patches with long sides in the y direction
   nfCoverZ - number of fibers in the cover patches with long sides in the z direction
   
                        y
                        ^
                        |     
             ---------------------    --   --
             ||   o     o     o    |     |    -- coverH
             |                    |     |
             |   o            o   |     |
    z <---   |          +         |     HSec
             |   o            o  |     |
             |                  |     |
             |   o o o o o o    |     |    -- coverH
             ---------------------    --   --
             |-------Bsec------|
             |---| coverB  |---|

                       y
                       ^
                       |    
             ---------------------
             |\      cover        /|
             | \------Top------/ |
             |c|                   |c|
             |o|                   |o|
  z <-----|v|       core      |v|  HSec
             |e|                   |e|
             |r|                    |r|
             | /-------Bot------\ |
             |/      cover        \|
             ---------------------
                       Bsec
    

 Notes
    The core concrete ends at the NA of the reinforcement
    The center of the section is at (0,0) in the local axis system
"""

# =========================================================================== 
# Import Libraries
# ===========================================================================
import opsvis as osv
import matplotlib.pyplot as plt
from LibUnits import *
from LibMaterialsRC import *

# ===========================================================================
# Main Code
# ===========================================================================
def BuildRCrectSection (id, HSec, BSec, coverH, coverB, coreID, coverID, 
                        steelID, numBarsTop, barAreaTop, numBarsBot, 
                        barAreaBot, numBarsIntTot, barAreaInt, nfCoreY, 
                        nfCoreZ, nfCoverY, nfCoverZ):
       
    coverY = HSec/2.0		# The distance from the section z-axis to the edge of the cover concrete -- outer edge of cover concrete
    coverZ = BSec/2.0		# The distance from the section y-axis to the edge of the cover concrete -- outer edge of cover concrete
    coreY = coverY-coverH		# The distance from the section z-axis to the edge of the core concrete --  edge of the core concrete/inner edge of cover concrete
    coreZ = coverZ-coverB		# The distance from the section y-axis to the edge of the core concrete --  edge of the core concrete/inner edge of cover concrete
    numBarsInt = int(numBarsIntTot/2)	# number of intermediate bars per side    



    secTag = id   # Fiber section tag
    
    fibSec = [['section', 'Fiber', secTag, '-GJ', 1e-10],
		      # Define the core patch
              ['patch', 'quadr', coreID, nfCoreZ, nfCoreY, *[-coreY, coreZ], *[-coreY, -coreZ], *[coreY, -coreZ], *[coreY, coreZ]],

		      # Define the four cover patches
              ['patch', 'quadr', coverID, 2, nfCoverY, *[-coverY, coverZ], *[-coreY, coreZ ], *[coreY, coreZ], *[coverY, coverZ]],
              ['patch', 'quadr', coverID, 2, nfCoverY, *[-coreY, -coreZ], *[-coverY, -coverZ], *[coverY, -coverZ], *[coreY, -coreZ]],            
              ['patch', 'quadr', coverID, nfCoverZ, 2, *[-coverY, coverZ], *[-coverY, -coverZ], *[-coreY, -coreZ], *[-coreY, coreZ]],        
              ['patch', 'quadr', coverID, nfCoverZ, 2, *[coreY, coreZ], *[coreY, -coreZ], *[coverY, -coverZ], *[coverY, coverZ]], 
            
              # define reinforcing layers
              ['layer', 'straight', steelID, numBarsInt, barAreaInt, *[-coreY,  coreZ], *[ coreY,  coreZ]], # intermediate skin reinf. +z
              ['layer', 'straight', steelID, numBarsInt, barAreaInt, *[-coreY, -coreZ], *[ coreY, -coreZ]], # intermediate skin reinf. -z
              ['layer', 'straight', steelID, numBarsTop, barAreaTop, *[ coreY,  coreZ], *[ coreY, -coreZ]], # top layer reinfocement
              ['layer', 'straight', steelID, numBarsBot, barAreaBot, *[-coreY,  coreZ], *[-coreY, -coreZ]]] # bottom layer reinforcement

    osv.fib_sec_list_to_cmds(fibSec) # This command converts the opsvis list to openseespy section object    
    
    osv.plot_fiber_section(fibSec)
    plt.axis('equal')
   





		
			
			
			
			

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    